### ISSUE TITLE
TypeError: tor.httpAgent is not a function

### ISSUE THREAD

**Issue by armmmo** [pelogvc/tor-axios#1]
httpAgent: tor.httpAgent(),
                   ^

TypeError: tor.httpAgent is not a function

using the axios example

**Comment by ghost** [comment]
+1
The following works for me:
`httpAgent: tor.defaults.httpAgent, httpsAgent: tor.defaults.httpsAgent`

**Comment by pelogvc** [comment]
thx :)
you can use `tor.httpAgent()` function.

I just updated 1.0.9.
