### ISSUE TITLE
Multiple security vulnerabilities due to old axios version

### ISSUE THREAD

**Issue by derMart** [pelogvc/tor-axios#10]
running npm audit reveals some vulnerabilities:
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Exposure of sensitive information in follow-redirects        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ follow-redirects                                             │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=1.14.7                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ tor-axios                                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ tor-axios > axios > follow-redirects                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://github.com/advisories/GHSA-74fj-2j2h-c42q            │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Server-Side Request Forgery in Axios                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ axios                                                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=0.21.1                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ tor-axios                                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ tor-axios > axios                                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://github.com/advisories/GHSA-4w2v-q235-vp99            │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Incorrect Comparison in axios                                │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ axios                                                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=0.21.2                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ tor-axios                                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ tor-axios > axios                                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://github.com/advisories/GHSA-cph5-m8f7-6c5x            │
└───────────────┴──────────────────────────────────────────────────────────────┘

please upstream to axios >=0.21.1 to fix this

**Comment by derMart** [comment]
Ok it seems this is already in the master branch, but my copy of tor-axios installed via npm still has an old version of axios.
Forgotten to release to npm?

**Comment by pelogvc** [comment]
updated axios version. thx
