### ISSUE TITLE
DNS isn't resolved through the proxy

### ISSUE THREAD

**Issue by ghost** [pelogvc/tor-axios#2]
Hostnames aren't being resolved through Tor. This is due to an incorrect proxy URL in both `httpAgent()` as well as `httpsAgent()`.
https://github.com/pelogvc/tor-axios/blob/master/index.js#L17

The protocol should be `socks5h` instead of `socks5`.
https://github.com/TooTallNate/node-socks-proxy-agent/blob/master/src/agent.ts#L63

**Comment by pelogvc** [comment]
thx :)

I just updated 1.0.9.
